name: ml_kit_face_dtector
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  avatar_glow: ^2.0.2
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  rive: ^0.9.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  speech_to_text: ^5.6.0
  substring_highlight: ^1.0.33
  url_launcher: ^6.1.4
  camera: ^0.10.0+1
  google_ml_kit: ^0.12.0
  image_picker: ^0.8.5+3
  logger: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
       - assets/

